### ISSUE TITLE
Quotes missing from $passfile variable on line 90

### ISSUE THREAD

**Issue by greywood** [elcorto/pass-cl#1]
I use subdirectories in my password-store and they sometimes include spaces.

I had to add quotes to the $passfile variable on line 90 of cl.bash so the line now reads:

[ -f "$passfile" ] || err "$path is not in the password store"

Otherwise it produced the error:

.pass_extensions/cl.bash: line 91: [: too many arguments

Thanks for the extension! It's exactly what I was looking for.

**Comment by elcorto** [comment]
Hi

Good catch, thanks for the feedback! If you want, please send a PR over. If you do, please use a commit prefix from [here](https://github.com/elcorto/libstuff/blob/master/commit_prefixes.rst), probably ENH or BUG.

Else I'll add the fix myself and cite you in the commit. Let me know.

**Comment by greywood** [comment]
Feel free to make the changes. Thanks.
